### ISSUE TITLE
Integrate Elastic

### ISSUE THREAD

**Issue by aridavidson001** [TitaniumTigers4829/4829-BaseRobotCode#8]
https://github.com/Gold872/elastic-dashboard

**Comment by Ishan1522** [comment]
I'd appreciate a slightly more in-depth description of what is happening here. Bc elastic just uses the Shuffleboard/Smartdashboard API, so nothing much would change about our code. The only elastic specific thing I see is the ElasticLib + Robot Notifications.

**Comment by aridavidson001** [comment]
okay, i'm not 100% sure what we should use the notifications for, but I definitely think they will be useful for debugging. Also, I think the swerve drive widget has some custom setup stuff.
![Image](https://github.com/user-attachments/assets/f629c69d-924f-400b-b25d-878173320137)

**Comment by Ishan1522** [comment]
No? That's still SmartDashboard (and can show up on Shuffleboard). Also this is somewhat encroaching upon what we are doing with AdvantageScope. Also, Alerts are already set up.

**Comment by aridavidson001** [comment]
okay ill delete this issue then
